"""An Ask answer as a self-contained HTML report (P4-U02 "Save as report").

A pure function of the stored answer (services/ask_outputs.answer_report_data): the result rows exactly as
the gateway returned them, the question, SQL, provenance and evidence state. No model text is included, so
every number in the document is a cell of the stored result. Every value is escaped (narrative.esc).
"""
from __future__ import annotations

from typing import Any

from analystos.reports import _common as C
from analystos.reports.narrative import _CSS, _html_table, esc

MAX_ROWS = 200

ANSWERED_BY = {"registry": "a verified query (no model)", "rules": "a rule built from the catalog (no model)",
               "semantic": "an approved metric calculation (no model)", "model": "SQL generated by a model, checked by the gateway",
               "sql": "the saved SQL, run again"}
BADGE_WORDS = {"verified": "verified", "pending": "verification pending", "void": "void: needs re-verification",
               "superseded": "superseded", "legacy": "verified by an older checker", "failed": "failed verification",
               "unverified": "not verified (record the thread as steps to self-check it)"}


def _kv(items: list[tuple[str, str]]) -> str:
    return _html_table(["", ""], [[f"<strong>{esc(k)}</strong>", v] for k, v in items])


def render_answer_html(d: dict[str, Any]) -> str:
    res = d.get("result") or {}
    columns = [str(c) for c in res.get("columns") or []]
    rows = list(res.get("rows") or [])
    shown = rows[:MAX_ROWS]
    row_count = res.get("row_count") if res.get("row_count") is not None else len(rows)
    summary = (f"{row_count} row{'s' if row_count != 1 else ''} from query <code>{esc(res.get('query_id') or 'unknown')}</code>, "
               f"answered by {esc(ANSWERED_BY.get(d.get('answered_by') or '', d.get('answered_by') or 'unknown'))}."
               + (" The result was truncated by the workspace row limit." if res.get("truncated") else ""))
    table = _html_table(columns, [[esc(C.cell_text(v)) for v in r] for r in shown], "data") if columns else "<p>No columns.</p>"
    if len(rows) > len(shown):
        table += f'<p class="small">Showing {len(shown)} of {len(rows)} stored rows.</p>'
    assets = d.get("assets") or []
    tables = _html_table(["Table", "Source", "Mode", "Data as of", "Rows"],
                         [[f"<code>{esc(a.get('asset'))}</code>", esc(a.get("source_name") or "unknown"), esc(a.get("execution_mode") or "unknown"),
                           esc(a.get("freshness_at") or "unknown"), esc(a.get("row_count") if a.get("row_count") is not None else "unknown")]
                          for a in assets]) if assets else "<p>No tables recorded.</p>"
    semantic = d.get("semantic") or {}
    prov = [("Governance", esc("governed (approved definitions)" if d.get("governance") == "governed" else "ad hoc calculation")),
            ("Query", f"<code>{esc(res.get('query_id') or '')}</code>"),
            ("Result hash", f"<code>{esc(res.get('result_hash') or '')}</code>")]
    if d.get("model"):
        prov.append(("Model that wrote the SQL", esc(d["model"])))
    if semantic:
        prov.append(("Semantic model", esc(f"version {semantic.get('model_version')}")))
        prov.append(("Metric definitions", esc(", ".join(semantic.get("metrics") or []) or "none")))
    fresh = d.get("staleness") or {}
    evidence = d.get("evidence_status") or {}
    verification = d.get("verification") or {}
    checks = [("Data freshness", esc(fresh.get("label") or "unknown")),
              ("Evidence", esc({"recorded": "recorded definitions unchanged", "changed": "changed since this answer: ask again",
                                "ad_hoc": "ad hoc: no approved definitions"}.get(evidence.get("state"), evidence.get("state") or "unknown"))),
              ("Verification", esc(BADGE_WORDS.get(verification.get("badge") or "unverified", verification.get("badge") or "unknown")))]
    reasons = "".join(f"<li>{esc(r)}</li>" for r in evidence.get("reasons") or [])
    title = d.get("title") or "Ask answer"
    head = (f'<header><h1>{esc(title)}</h1><div class="meta">Ask answer · {esc(d.get("workspace_name") or "")} · '
            f'answered {esc(d.get("answered_at") or "")}</div></header>')
    body = (f'<section><h2>Answer</h2><p>{summary}</p>{table}</section>'
            f'<section><h2>SQL</h2><pre><code>{esc(d.get("sql") or "")}</code></pre></section>'
            f'<section><h2>Where the numbers come from</h2>{tables}{_kv(prov)}</section>'
            f'<section><h2>Verification</h2>{_kv(checks)}' + (f"<ul>{reasons}</ul>" if reasons else "") + "</section>")
    footer = (f'<footer><h2>{C.SECTION_TITLES["provenance"]}</h2><ul><li>Question: <code>{esc(d.get("turn_id"))}</code> in thread '
              f'<code>{esc(d.get("thread_id"))}</code></li><li>Every number above is a cell of the stored query result; no text '
              f'in this report was written by a model.</li></ul><p class="note">{esc(C.CAUSATION_NOTE)}</p></footer>')
    return ("<!DOCTYPE html>\n"
            '<html lang="en"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width,initial-scale=1">'
            "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; style-src 'unsafe-inline'; img-src data:\">"
            f"<title>{esc(title)}</title><style>{_CSS}</style></head>"
            f'<body><main class="kind-ask">{head}\n{body}\n{footer}</main></body></html>\n')


__all__ = ["render_answer_html"]
