"""control plane schema v1

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 04:46:00.569205
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definition',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('agent_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_message_run_id'), 'agent_message', ['run_id'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('approval',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('risk_tier', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=True),
    sa.Column('affected_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=40), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_run_id'), 'approval', ['run_id'], unique=False)
    op.create_index(op.f('ix_approval_workspace_id'), 'approval', ['workspace_id'], unique=False)
    op.create_table('artifact',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('creator_agent', sa.String(length=80), nullable=True),
    sa.Column('creator_user', sa.String(length=40), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_run_id'), 'artifact', ['run_id'], unique=False)
    op.create_index(op.f('ix_artifact_type'), 'artifact', ['type'], unique=False)
    op.create_index(op.f('ix_artifact_workspace_id'), 'artifact', ['workspace_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=True),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_workspace_id'), 'audit_event', ['workspace_id'], unique=False)
    op.create_table('context_entry',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapped_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_entry_workspace_id'), 'context_entry', ['workspace_id'], unique=False)
    op.create_table('experiment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=40), nullable=True),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('query_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_hypothesis_id'), 'experiment', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_experiment_run_id'), 'experiment', ['run_id'], unique=False)
    op.create_index(op.f('ix_experiment_workspace_id'), 'experiment', ['workspace_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_run_id'), 'feedback', ['run_id'], unique=False)
    op.create_index(op.f('ix_feedback_workspace_id'), 'feedback', ['workspace_id'], unique=False)
    op.create_table('hypothesis',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=40), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_run_id'), 'hypothesis', ['run_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_workspace_id'), 'hypothesis', ['workspace_id'], unique=False)
    op.create_table('insight',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=40), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('population_size', sa.BigInteger(), nullable=False),
    sa.Column('business_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('caveats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('narrative_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_run_id'), 'insight', ['run_id'], unique=False)
    op.create_index(op.f('ix_insight_workspace_id'), 'insight', ['workspace_id'], unique=False)
    op.create_table('lineage_edge',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('from_type', sa.String(length=40), nullable=False),
    sa.Column('from_id', sa.String(length=200), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.Column('to_type', sa.String(length=40), nullable=False),
    sa.Column('to_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_type', 'from_id', 'relation', 'to_type', 'to_id')
    )
    op.create_index(op.f('ix_lineage_edge_workspace_id'), 'lineage_edge', ['workspace_id'], unique=False)
    op.create_table('model_call',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=True),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('agent_id', sa.String(length=80), nullable=True),
    sa.Column('purpose', sa.String(length=60), nullable=False),
    sa.Column('profile', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_call_run_id'), 'model_call', ['run_id'], unique=False)
    op.create_index(op.f('ix_model_call_workspace_id'), 'model_call', ['workspace_id'], unique=False)
    op.create_table('publication',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('approval_id', sa.String(length=40), nullable=True),
    sa.Column('destination', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_publication_workspace_id'), 'publication', ['workspace_id'], unique=False)
    op.create_table('query_execution',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=40), nullable=True),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=120), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('executed_sql', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('referenced_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('result_preview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_execution_fingerprint'), 'query_execution', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_query_execution_run_id'), 'query_execution', ['run_id'], unique=False)
    op.create_index(op.f('ix_query_execution_workspace_id'), 'query_execution', ['workspace_id'], unique=False)
    op.create_table('relationship',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('from_asset_id', sa.String(length=40), nullable=False),
    sa.Column('from_column', sa.String(length=200), nullable=False),
    sa.Column('to_asset_id', sa.String(length=40), nullable=False),
    sa.Column('to_column', sa.String(length=200), nullable=False),
    sa.Column('cardinality', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_workspace_id'), 'relationship', ['workspace_id'], unique=False)
    op.create_table('run_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_event_run_id'), 'run_event', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_event_workspace_id'), 'run_event', ['workspace_id'], unique=False)
    op.create_table('skill_definition',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_definition',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_execution',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('agent_id', sa.String(length=80), nullable=True),
    sa.Column('tool_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_execution_run_id'), 'tool_execution', ['run_id'], unique=False)
    op.create_index(op.f('ix_tool_execution_workspace_id'), 'tool_execution', ['workspace_id'], unique=False)
    op.create_table('artifact_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'version')
    )
    op.create_index(op.f('ix_artifact_version_artifact_id'), 'artifact_version', ['artifact_id'], unique=False)
    op.create_table('workspace',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('autonomy_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_run',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('autonomy_level', sa.Integer(), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('control', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=40), nullable=False),
    sa.Column('workflow_id', sa.String(length=120), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_run_workspace_id'), 'analysis_run', ['workspace_id'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_ref', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('staging_schema', sa.String(length=80), nullable=True),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_workspace_id'), 'source', ['workspace_id'], unique=False)
    op.create_table('workspace_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_index(op.f('ix_workspace_member_user_id'), 'workspace_member', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_workspace_id'), 'workspace_member', ['workspace_id'], unique=False)
    op.create_table('workspace_policy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'version')
    )
    op.create_index(op.f('ix_workspace_policy_workspace_id'), 'workspace_policy', ['workspace_id'], unique=False)
    op.create_table('run_task',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('agent_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'key')
    )
    op.create_index(op.f('ix_run_task_run_id'), 'run_task', ['run_id'], unique=False)
    op.create_table('source_asset',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('schema_name', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('freshness_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'schema_name', 'name')
    )
    op.create_index(op.f('ix_source_asset_source_id'), 'source_asset', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_asset_workspace_id'), 'source_asset', ['workspace_id'], unique=False)
    op.create_table('source_column',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=80), nullable=False),
    sa.Column('semantic_type', sa.String(length=40), nullable=True),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('is_key', sa.Boolean(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['source_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'name')
    )
    op.create_index(op.f('ix_source_column_asset_id'), 'source_column', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_column_asset_id'), table_name='source_column')
    op.drop_table('source_column')
    op.drop_index(op.f('ix_source_asset_workspace_id'), table_name='source_asset')
    op.drop_index(op.f('ix_source_asset_source_id'), table_name='source_asset')
    op.drop_table('source_asset')
    op.drop_index(op.f('ix_run_task_run_id'), table_name='run_task')
    op.drop_table('run_task')
    op.drop_index(op.f('ix_workspace_policy_workspace_id'), table_name='workspace_policy')
    op.drop_table('workspace_policy')
    op.drop_index(op.f('ix_workspace_member_workspace_id'), table_name='workspace_member')
    op.drop_index(op.f('ix_workspace_member_user_id'), table_name='workspace_member')
    op.drop_table('workspace_member')
    op.drop_index(op.f('ix_source_workspace_id'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_analysis_run_workspace_id'), table_name='analysis_run')
    op.drop_table('analysis_run')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_artifact_version_artifact_id'), table_name='artifact_version')
    op.drop_table('artifact_version')
    op.drop_index(op.f('ix_tool_execution_workspace_id'), table_name='tool_execution')
    op.drop_index(op.f('ix_tool_execution_run_id'), table_name='tool_execution')
    op.drop_table('tool_execution')
    op.drop_table('tool_definition')
    op.drop_table('skill_definition')
    op.drop_index(op.f('ix_run_event_workspace_id'), table_name='run_event')
    op.drop_index(op.f('ix_run_event_run_id'), table_name='run_event')
    op.drop_table('run_event')
    op.drop_index(op.f('ix_relationship_workspace_id'), table_name='relationship')
    op.drop_table('relationship')
    op.drop_index(op.f('ix_query_execution_workspace_id'), table_name='query_execution')
    op.drop_index(op.f('ix_query_execution_run_id'), table_name='query_execution')
    op.drop_index(op.f('ix_query_execution_fingerprint'), table_name='query_execution')
    op.drop_table('query_execution')
    op.drop_index(op.f('ix_publication_workspace_id'), table_name='publication')
    op.drop_table('publication')
    op.drop_index(op.f('ix_model_call_workspace_id'), table_name='model_call')
    op.drop_index(op.f('ix_model_call_run_id'), table_name='model_call')
    op.drop_table('model_call')
    op.drop_index(op.f('ix_lineage_edge_workspace_id'), table_name='lineage_edge')
    op.drop_table('lineage_edge')
    op.drop_index(op.f('ix_insight_workspace_id'), table_name='insight')
    op.drop_index(op.f('ix_insight_run_id'), table_name='insight')
    op.drop_table('insight')
    op.drop_index(op.f('ix_hypothesis_workspace_id'), table_name='hypothesis')
    op.drop_index(op.f('ix_hypothesis_run_id'), table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_index(op.f('ix_feedback_workspace_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_run_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_experiment_workspace_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_run_id'), table_name='experiment')
    op.drop_index(op.f('ix_experiment_hypothesis_id'), table_name='experiment')
    op.drop_table('experiment')
    op.drop_index(op.f('ix_context_entry_workspace_id'), table_name='context_entry')
    op.drop_table('context_entry')
    op.drop_index(op.f('ix_audit_event_workspace_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_artifact_workspace_id'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_type'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_run_id'), table_name='artifact')
    op.drop_table('artifact')
    op.drop_index(op.f('ix_approval_workspace_id'), table_name='approval')
    op.drop_index(op.f('ix_approval_run_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_agent_message_run_id'), table_name='agent_message')
    op.drop_table('agent_message')
    op.drop_table('agent_definition')
    # ### end Alembic commands ###
