"""widen insight narrative_source

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 05:24:14.587338
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insight', 'narrative_source',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=160),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insight', 'narrative_source',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
