"""phase 3 schedules monitors alerts notifications

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 06:00:46.316277
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('monitor_id', sa.String(length=40), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('investigation_run_id', sa.String(length=40), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_dedupe_key'), 'alert', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_alert_monitor_id'), 'alert', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_alert_workspace_id'), 'alert', ['workspace_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_by', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_workspace_id'), 'notification', ['workspace_id'], unique=False)
    op.create_table('monitor',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_investigate', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_workspace_id'), 'monitor', ['workspace_id'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('cron', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(length=40), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_next_run_at'), 'schedule', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedule_workspace_id'), 'schedule', ['workspace_id'], unique=False)
    op.create_table('schedule_run',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('schedule_id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('fire_key', sa.String(length=120), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fire_key')
    )
    op.create_index(op.f('ix_schedule_run_schedule_id'), 'schedule_run', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_run_workspace_id'), 'schedule_run', ['workspace_id'], unique=False)
    op.add_column('analysis_run', sa.Column('origin', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_run', 'origin')
    op.drop_index(op.f('ix_schedule_run_workspace_id'), table_name='schedule_run')
    op.drop_index(op.f('ix_schedule_run_schedule_id'), table_name='schedule_run')
    op.drop_table('schedule_run')
    op.drop_index(op.f('ix_schedule_workspace_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_next_run_at'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_monitor_workspace_id'), table_name='monitor')
    op.drop_table('monitor')
    op.drop_index(op.f('ix_notification_workspace_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_alert_workspace_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_monitor_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_dedupe_key'), table_name='alert')
    op.drop_table('alert')
    # ### end Alembic commands ###
