"""crawler state and crawl runs

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-25 14:15:27.716384
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_run',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_by', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_run_source_id'), 'crawl_run', ['source_id'], unique=False)
    op.create_index(op.f('ix_crawl_run_workspace_id'), 'crawl_run', ['workspace_id'], unique=False)
    op.add_column('source_asset', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('source_asset', sa.Column('lifecycle', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('source_asset', sa.Column('semantics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('source_asset', sa.Column('description_origin', sa.String(length=20), nullable=True))
    op.add_column('source_asset', sa.Column('business_name_origin', sa.String(length=20), nullable=True))
    op.add_column('source_asset', sa.Column('reviewed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('source_asset', sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('source_column', sa.Column('semantics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('source_column', sa.Column('tags_origin', sa.String(length=20), server_default='crawler', nullable=False))
    # Only an owner could set "restricted" before this revision: keep those tags out of crawler reach.
    op.execute("UPDATE source_column SET tags_origin = 'user' WHERE tags::jsonb ? 'restricted'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_column', 'tags_origin')
    op.drop_column('source_column', 'semantics')
    op.drop_column('source_asset', 'last_crawled_at')
    op.drop_column('source_asset', 'reviewed')
    op.drop_column('source_asset', 'business_name_origin')
    op.drop_column('source_asset', 'description_origin')
    op.drop_column('source_asset', 'semantics')
    op.drop_column('source_asset', 'lifecycle')
    op.drop_column('source_asset', 'fingerprint')
    op.drop_index(op.f('ix_crawl_run_workspace_id'), table_name='crawl_run')
    op.drop_index(op.f('ix_crawl_run_source_id'), table_name='crawl_run')
    op.drop_table('crawl_run')
    # ### end Alembic commands ###
