"""model call replay: content-addressed request/response payloads (P4-C09)

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-25 18:00:00

Hand-written (not autogenerated): another migration (0007) is developed in parallel.
"""
from alembic import op
import sqlalchemy as sa

revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('model_payload',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.add_column('model_call', sa.Column('request_ref', sa.String(length=64), nullable=True))
    op.add_column('model_call', sa.Column('response_ref', sa.String(length=64), nullable=True))


def downgrade() -> None:
    op.drop_column('model_call', 'response_ref')
    op.drop_column('model_call', 'request_ref')
    op.drop_table('model_payload')
