"""prompt cache accounting and context receipts on model_call (P4-T04, P4-T03)

Revision ID: 0014
Revises: 0011
Create Date: 2026-09-25 22:00:00

Hand-written (not autogenerated): other increment-4 migrations are developed in parallel; the
coordinator re-chains `down_revision` when the streams merge.
"""
from alembic import op
import sqlalchemy as sa

revision = '0014'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('model_call', sa.Column('cached_input_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('model_call', sa.Column('context_receipts', sa.JSON(), nullable=True))


def downgrade() -> None:
    op.drop_column('model_call', 'context_receipts')
    op.drop_column('model_call', 'cached_input_tokens')
