"""knowledge packs (OKF v0.2 system of record), revisions, and the rebuildable knowledge index;
NULL-workspace context_entry rows move into the read-only platform pack (P4-K01, P4-K10)

Revision ID: 0018
Revises: 0023
Create Date: 2026-09-25 23:30:00

Hand-written (not autogenerated): other increment-4 migrations are developed in parallel; the
coordinator re-chains `down_revision` when the streams merge.

Data step: every `context_entry` row with a NULL workspace becomes an OKF concept document in
revision 1 of the `platform` pack (the renderer is inlined so this migration does not change when
application code does), then the rows are deleted and `workspace_id` becomes NOT NULL. The index
tables start empty: `analystos migrate` indexes new pack revisions after upgrading, and
`analystos knowledge reindex` rebuilds everything. Downgrade restores the rows from the pack.
"""
import hashlib
import json
import re
import secrets

import sqlalchemy as sa
import yaml
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = "0018"
down_revision = "0023"
branch_labels = None
depends_on = None

OKF_SPEC_REVISION = "0b87c52c6ef999286c745e19998fdfcd03d5dbee"
OKF_SPEC_SHA256 = "26aa5da029278939f914e578107242d9607d4f2dc5fe153272b82f9ed1030101"
KIND_TYPES = {"term": "Glossary Term", "definition": "Definition", "metric": "Metric", "rule": "Business Rule",
              "note": "Note", "dashboard": "Dashboard", "table": "Table"}
KIND_HEADINGS = {"term": "Definition", "definition": "Definition", "metric": "Definition", "rule": "Rule"}


def upgrade() -> None:
    op.create_table(
        "knowledge_pack",
        sa.Column("id", sa.String(40), primary_key=True),
        sa.Column("workspace_id", sa.String(40), sa.ForeignKey("workspace.id", ondelete="CASCADE"), nullable=True),
        sa.Column("kind", sa.String(20), nullable=False),
        sa.Column("slug", sa.String(120), nullable=False),
        sa.Column("title", sa.String(300), nullable=False, server_default=""),
        sa.Column("read_only", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("okf_version", sa.String(10), nullable=False, server_default="0.2"),
        sa.Column("okf_spec_revision", sa.String(64), nullable=False),
        sa.Column("okf_spec_sha256", sa.String(64), nullable=False),
        sa.Column("okf_root", sa.String(200), nullable=False, server_default=""),
        sa.Column("head_revision", sa.Integer(), nullable=True),
        sa.Column("git_remote", sa.String(500), nullable=True),
        sa.Column("git_branch", sa.String(120), nullable=False, server_default="main"),
        sa.Column("origin", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("workspace_id", "slug"),
        sa.CheckConstraint("(kind = 'platform') = (workspace_id IS NULL)", name="ck_knowledge_pack_platform_scope"),
    )
    op.create_index("ix_knowledge_pack_workspace_id", "knowledge_pack", ["workspace_id"])
    op.create_index("uq_knowledge_pack_platform_slug", "knowledge_pack", ["slug"], unique=True,
                    postgresql_where=sa.text("workspace_id IS NULL"))
    op.create_table(
        "knowledge_object",
        sa.Column("pack_id", sa.String(40), sa.ForeignKey("knowledge_pack.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("sha256", sa.String(64), primary_key=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table(
        "knowledge_revision",
        sa.Column("id", sa.String(40), primary_key=True),
        sa.Column("pack_id", sa.String(40), sa.ForeignKey("knowledge_pack.id", ondelete="CASCADE"), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("parent_number", sa.Integer(), nullable=True),
        sa.Column("author", sa.String(200), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("origin", sa.String(30), nullable=False),
        sa.Column("files", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("content_digest", sa.String(64), nullable=False),
        sa.Column("meta", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("pack_id", "number"),
    )
    op.create_index("ix_knowledge_revision_pack_id", "knowledge_revision", ["pack_id"])
    op.create_table(
        "knowledge_document",
        sa.Column("id", sa.String(40), primary_key=True),
        sa.Column("pack_id", sa.String(40), sa.ForeignKey("knowledge_pack.id", ondelete="CASCADE"), nullable=False),
        sa.Column("workspace_id", sa.String(40), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(500), nullable=False),
        sa.Column("concept_id", sa.String(500), nullable=False),
        sa.Column("type", sa.String(120), nullable=False),
        sa.Column("kind", sa.String(40), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("trust_tier", sa.String(30), nullable=False),
        sa.Column("stale_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("frontmatter", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("body", sa.Text(), nullable=False, server_default=""),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.UniqueConstraint("pack_id", "path"),
    )
    for col in ("pack_id", "workspace_id", "type", "kind"):
        op.create_index(f"ix_knowledge_document_{col}", "knowledge_document", [col])
    op.create_table(
        "knowledge_section",
        sa.Column("id", sa.String(40), primary_key=True),
        sa.Column("document_id", sa.String(40), sa.ForeignKey("knowledge_document.id", ondelete="CASCADE"), nullable=False),
        sa.Column("pack_id", sa.String(40), nullable=False),
        sa.Column("workspace_id", sa.String(40), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("anchor", sa.String(200), nullable=False),
        sa.Column("heading", sa.String(500), nullable=False, server_default=""),
        sa.Column("text", sa.Text(), nullable=False, server_default=""),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False, server_default=""),
        sa.Column("tsv", postgresql.TSVECTOR(),
                  sa.Computed("to_tsvector('english', coalesce(search_text, ''))", persisted=True)),
        sa.Column("embedding", Vector(256), nullable=True),
        sa.Column("embedding_model", sa.String(200), nullable=True),
        sa.UniqueConstraint("document_id", "anchor"),
    )
    for col in ("document_id", "pack_id", "workspace_id"):
        op.create_index(f"ix_knowledge_section_{col}", "knowledge_section", [col])
    op.create_index("ix_knowledge_section_tsv", "knowledge_section", ["tsv"], postgresql_using="gin")
    op.create_index("ix_knowledge_section_embedding_hnsw", "knowledge_section", ["embedding"], postgresql_using="hnsw",
                    postgresql_ops={"embedding": "vector_cosine_ops"})
    op.create_table(
        "knowledge_link",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("pack_id", sa.String(40), nullable=False),
        sa.Column("workspace_id", sa.String(40), nullable=True),
        sa.Column("source_path", sa.String(500), nullable=False),
        sa.Column("raw", sa.String(2000), nullable=False),
        sa.Column("kind", sa.String(20), nullable=False),
        sa.Column("target_path", sa.String(500), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index("ix_knowledge_link_pack_id", "knowledge_link", ["pack_id"])
    op.create_index("ix_knowledge_link_workspace_id", "knowledge_link", ["workspace_id"])
    op.create_table(
        "knowledge_index_state",
        sa.Column("key", sa.String(80), primary_key=True),
        sa.Column("value", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    _move_global_entries_to_platform_pack()
    op.alter_column("context_entry", "workspace_id", existing_type=sa.String(40), nullable=False)


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:80].strip("-") or "entry"


def _render(row) -> str:
    kind = row.kind
    trusted = bool(row.trusted)
    ext = {"kind": kind, "origin": row.origin or "user", "trusted": trusted}
    if row.synonyms:
        ext["synonyms"] = list(row.synonyms)
    if row.mapped_columns:
        ext["mapped_columns"] = list(row.mapped_columns)
    pack = (row.origin or "")[5:] if (row.origin or "").startswith("pack:") else None
    if pack:
        ext["domain_pack"] = pack
    fm = {"type": KIND_TYPES.get(kind, kind.title()), "title": row.name, "analystos": ext,
          "status": "stable" if trusted else "draft", "generated": {"by": "process:analystos-migration-0018"},
          "tags": sorted({kind, *([f"domain-{pack}"] if pack else [])})}
    flat = " ".join((row.body or "").split())
    if flat:
        m = re.search(r"(?<=[.!?])\s", flat)
        first = flat[: m.start()] if m else flat
        fm["description"] = first if len(first) <= 240 else first[:239].rstrip() + "…"
    heading = KIND_HEADINGS.get(kind)
    body = row.body or ""
    text = f"# {heading}\n\n{body.strip()}" if heading and not body.lstrip().startswith("#") else body
    dumped = yaml.safe_dump(fm, sort_keys=True, allow_unicode=True, default_flow_style=False, width=4096)
    return f"---\n{dumped}---\n\n{text.strip()}\n"


def _move_global_entries_to_platform_pack() -> None:
    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id, kind, name, body, synonyms, mapped_columns, origin, trusted "
                                "FROM context_entry WHERE workspace_id IS NULL ORDER BY id")).all()
    if not rows:
        return
    files: dict[str, bytes] = {}
    for row in rows:
        origin = row.origin or ""
        base = f"domain/{_slug(origin[5:])}" if origin.startswith("pack:") else f"platform/{_slug(row.kind)}"
        path = f"{base}/{_slug(row.name)}.md"
        while path in files:
            path = path[:-3] + "-x.md"
        files[path] = _render(row).encode()
    files["index.md"] = b"---\nokf_version: '0.2'\n---\n\n# Platform knowledge\n\nMigrated from global context entries.\n"
    pack_id = f"kpk_{secrets.token_hex(6)}"
    bind.execute(sa.text("INSERT INTO knowledge_pack (id, workspace_id, kind, slug, title, read_only, okf_version, "
                         "okf_spec_revision, okf_spec_sha256, okf_root, head_revision, git_branch, origin) VALUES "
                         "(:id, NULL, 'platform', 'platform', 'Platform knowledge', true, '0.2', :rev, :sha, '', 1, 'main', "
                         "CAST(:origin AS jsonb))"),
                 {"id": pack_id, "rev": OKF_SPEC_REVISION, "sha": OKF_SPEC_SHA256,
                  "origin": json.dumps({"migrated_from": "context_entry"})})
    shas = {}
    for path, data in sorted(files.items()):
        sha = hashlib.sha256(data).hexdigest()
        shas[path] = sha
        bind.execute(sa.text("INSERT INTO knowledge_object (pack_id, sha256, size, content) VALUES (:p, :s, :n, :c) "
                             "ON CONFLICT DO NOTHING"), {"p": pack_id, "s": sha, "n": len(data), "c": data})
    digest = hashlib.sha256("".join(f"{p}\0{shas[p]}\n" for p in sorted(shas)).encode()).hexdigest()
    bind.execute(sa.text("INSERT INTO knowledge_revision (id, pack_id, number, parent_number, author, reason, origin, files, "
                         "content_digest, meta) VALUES (:id, :p, 1, NULL, 'process:analystos-migration-0018', "
                         "'global context entries moved into the platform pack', 'migration', CAST(:files AS jsonb), :d, "
                         "CAST(:meta AS jsonb))"),
                 {"id": f"krev_{secrets.token_hex(6)}", "p": pack_id, "files": json.dumps(dict(sorted(shas.items()))),
                  "d": digest, "meta": json.dumps({"migrated_rows": len(rows)})})
    bind.execute(sa.text("DELETE FROM context_entry WHERE workspace_id IS NULL"))


def downgrade() -> None:
    op.alter_column("context_entry", "workspace_id", existing_type=sa.String(40), nullable=True)
    _restore_global_entries()
    for table in ("knowledge_index_state", "knowledge_link", "knowledge_section", "knowledge_document",
                  "knowledge_revision", "knowledge_object", "knowledge_pack"):
        op.drop_table(table)


def _restore_global_entries() -> None:
    """Platform-pack documents with an `analystos` extension become NULL-workspace entries again."""
    bind = op.get_bind()
    pack = bind.execute(sa.text("SELECT id, head_revision FROM knowledge_pack WHERE kind = 'platform'")).first()
    if pack is None or pack.head_revision is None:
        return
    files = bind.execute(sa.text("SELECT files FROM knowledge_revision WHERE pack_id = :p AND number = :n"),
                         {"p": pack.id, "n": pack.head_revision}).scalar() or {}
    try:
        from analystos.context.embeddings import embed
    except Exception:  # noqa: BLE001 - restore without embeddings rather than not at all
        embed = None
    for path, sha in sorted(files.items()):
        if not path.endswith(".md") or path.rsplit("/", 1)[-1] in ("index.md", "log.md"):
            continue
        data = bind.execute(sa.text("SELECT content FROM knowledge_object WHERE pack_id = :p AND sha256 = :s"),
                            {"p": pack.id, "s": sha}).scalar()
        text = bytes(data).decode("utf-8")
        m = re.match(r"\A---\n(.*?)\n---\n?(.*)\Z", text, re.S)
        if not m:
            continue
        fm = yaml.safe_load(m.group(1)) or {}
        ext = fm.get("analystos") if isinstance(fm.get("analystos"), dict) else None
        if not ext or not ext.get("kind"):
            continue
        body = re.sub(r"\A\s*# [^\n]*\n+", "", m.group(2).strip(), count=1).strip()
        name = str(fm.get("title") or path)
        synonyms = list(ext.get("synonyms") or [])
        vector = embed(" ".join([name, body, *synonyms])) if embed else None
        bind.execute(sa.text("INSERT INTO context_entry (id, workspace_id, kind, name, body, synonyms, mapped_columns, "
                             "origin, trusted, embedding) VALUES (:id, NULL, :k, :n, :b, CAST(:s AS jsonb), "
                             "CAST(:m AS jsonb), :o, :t, CAST(:e AS vector))"),
                     {"id": f"ctx_{secrets.token_hex(6)}", "k": ext["kind"], "n": name[:300], "b": body,
                      "s": json.dumps(synonyms), "m": json.dumps(list(ext.get("mapped_columns") or [])),
                      "o": str(ext.get("origin") or "user")[:30], "t": bool(ext.get("trusted", True)),
                      "e": ("[" + ",".join(f"{x:.7g}" for x in vector) + "]") if vector else None})
